#!/bin/bash
#Initialization
WORKING_DIRECTORY=$(echo $PWD)
echo 'Working directory is: '$WORKING_DIRECTORY

#MASTER parameters used across all models
INPUT_FILE='data/data_20220215.csv' #File to be converted in Convertool
MODEL_DATE_MAX='2022-02-13' #Upper boundary of the modeling horizon

#Model estimation in batch

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'IOmicronInteractions' --ctooltype 'vo' --modelformula 'VII' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'HOmicronInteractions' --ctooltype 'ho' --modelformula 'VHI' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch_ct27 --inputfile $INPUT_FILE --modelname 'OOmicronInteractions' --ctooltype 'oo' --modelformula 'VOI' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch_ct27 --inputfile $INPUT_FILE --modelname 'UOmicronInteractions' --ctooltype 'oo' --modelformula 'VUI' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'ROmicron' --ctooltype 'ro' --modelformula 'VR' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'IOmicronDetail' --ctooltype 'vo+' --modelformula 'VI' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'HOmicronDetail' --ctooltype 'ho+' --modelformula 'VH' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'OOmicronDetail' --ctooltype 'ho+' --modelformula 'VO' --modeldate $MODEL_DATE_MAX --modelage '0 650';


echo 'Group done'
