#!/bin/bash
#Initialization
WORKING_DIRECTORY=$(echo $PWD)
echo 'Working directory is: '$WORKING_DIRECTORY

#MASTER parameters used across all models
INPUT_FILE='data/data_20220215.csv' #File to be converted in Convertool
MODEL_DATE_MAX='2022-02-13' #Upper boundary of the modeling horizon

#Model estimation in batch

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'IOmicronInteractions' --ctooltype 'vo:boost2+_inf6-' --modelformula 'VII' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch_ct27 --inputfile $INPUT_FILE --modelname 'HOmicronInteractions' --ctooltype 'ho:boost2+_inf6-,inf6-_boost2-,inf6-_full2-' --modelformula 'VHI' --modeldate $MODEL_DATE_MAX --modelage '0 650';



echo 'Group done'
