#!/bin/bash
#Initialization
WORKING_DIRECTORY=$(echo $PWD)
echo 'Working directory is: '$WORKING_DIRECTORY

#MASTER parameters used across all models
INPUT_FILE='data/data_20220215.csv' #File to be converted in Convertool
MODEL_DATE_MAX='2022-02-13' #Upper boundary of the modeling horizon

#Model estimation in batch

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'IDeltaInteractions' --ctooltype 'vd' --modelformula 'VII' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch_ct27 --inputfile $INPUT_FILE --modelname 'HDeltaInteractions' --ctooltype 'hd' --modelformula 'VHI' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch_ct27 --inputfile $INPUT_FILE --modelname 'ODeltaInteractions' --ctooltype 'od' --modelformula 'VOI' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch_ct27 --inputfile $INPUT_FILE --modelname 'UDeltaInteractions' --ctooltype 'ud' --modelformula 'VUI' --modeldate $MODEL_DATE_MAX --modelage '0 650';


./cox/cox_batch --inputfile $INPUT_FILE --modelname 'RDelta' --ctooltype 'rd' --modelformula 'VR' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'IDeltaDetail' --ctooltype 'vd+' --modelformula 'VI' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'HDeltaDetail' --ctooltype 'hd+' --modelformula 'VH' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'ODeltaDetail' --ctooltype 'hd+' --modelformula 'VO' --modeldate $MODEL_DATE_MAX --modelage '0 650';

echo 'Group done'
