#!/bin/bash
#Initialization
WORKING_DIRECTORY=$(echo $PWD)
echo 'Working directory is: '$WORKING_DIRECTORY

#MASTER parameters used across all models
INPUT_FILE='data/data_20220215.csv' #File to be converted in Convertool
MODEL_DATE_MAX='2022-02-13' #Upper boundary of the modeling horizon

#Model estimation in batch

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'IDeltaInteractions' --ctooltype 'vd:boost2+_inf6-,inf6-_boost2+,inf6-_full2-' --modelformula 'VII' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch_ct27 --inputfile $INPUT_FILE --modelname 'HDeltaInteractions' --ctooltype 'hd:inf6-_alone,inf6-_boost2-,inf6-_boost2+,inf6-_full2-,inf6-_full2+,boost2+_inf6-' --modelformula 'VHI' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch_ct27 --inputfile $INPUT_FILE --modelname 'ODeltaInteractions' --ctooltype 'od:inf6-_alone,12-15,16-17' --modelformula 'VOI' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch_ct27 --inputfile $INPUT_FILE --modelname 'UDeltaInteractions' --ctooltype 'ud:inf6-_alone,12-15' --modelformula 'VUI' --modeldate $MODEL_DATE_MAX --modelage '0 650';

./cox/cox_batch --inputfile $INPUT_FILE --modelname 'HDeltaDetail' --ctooltype 'hd+:Mfull1,Mpart2,inf1' --modelformula 'VH' --modeldate $MODEL_DATE_MAX --modelage '0 650';

echo 'Group done'
